### ISSUE TITLE
Update Lisa Wade's name

### ISSUE THREAD

**Issue by LisaCBrown** [OpenWaterFoundation/cdss-model-cu-sw-yampa#3]
Please update Lisa Wade to Lisa Brown (and the linked email address) under the "Maintainers" section.

**Comment by smalers** [comment]
Lisa has write permissions to the repository and can update that information herself, as well as other content.  Also, all issues should be given some labels when added so it is clear whether a bug, etc.  Lisa can clarify such things.

**Comment by LisaCBrown** [comment]
Completed
